apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-service
  namespace: aks-demo-ns
spec:
  type: LoadBalancer
  selector:
    app: nodejsapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
